default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nycrb_meetup_development

test:
  <<: *default
  database: nycrb_meetup_test

production:
  <<: *default
  database: nycrb_meetup_production
